create table countries
(
    id        INT not null
        primary key,
    name      VARCHAR    not null,
    continent VARCHAR    not null
);

INSERT INTO countries (id, name, continent) VALUES (1, 'Bermuda', 'North America');
INSERT INTO countries (id, name, continent) VALUES (2, 'Canada', 'North America');
INSERT INTO countries (id, name, continent) VALUES (3, 'Greenland', 'North America');
INSERT INTO countries (id, name, continent) VALUES (4, 'Mexico', 'North America');
INSERT INTO countries (id, name, continent) VALUES (5, 'Saint Pierre and Miquelon', 'North America');
INSERT INTO countries (id, name, continent) VALUES (6, 'United States', 'North America');
INSERT INTO countries (id, name, continent) VALUES (7, 'Antigua and Barbuda', 'North America');
INSERT INTO countries (id, name, continent) VALUES (8, 'Argentina', 'South America');
INSERT INTO countries (id, name, continent) VALUES (9, 'Aruba', 'North America');
INSERT INTO countries (id, name, continent) VALUES (10, 'Bahamas, The', 'North America');
INSERT INTO countries (id, name, continent) VALUES (11, 'Barbados', 'North America');
INSERT INTO countries (id, name, continent) VALUES (12, 'Belize', 'North America');
INSERT INTO countries (id, name, continent) VALUES (13, 'Bolivia', 'South America');
INSERT INTO countries (id, name, continent) VALUES (14, 'Brazil', 'South America');
INSERT INTO countries (id, name, continent) VALUES (15, 'Cayman Islands', 'North America');
INSERT INTO countries (id, name, continent) VALUES (16, 'Chile', 'South America');
INSERT INTO countries (id, name, continent) VALUES (17, 'Colombia', 'South America');
INSERT INTO countries (id, name, continent) VALUES (18, 'Costa Rica', 'North America');
INSERT INTO countries (id, name, continent) VALUES (19, 'Cuba', 'North America');
INSERT INTO countries (id, name, continent) VALUES (20, 'Dominica', 'North America');
INSERT INTO countries (id, name, continent) VALUES (21, 'Dominican Republic', 'North America');
INSERT INTO countries (id, name, continent) VALUES (22, 'Ecuador', 'South America');
INSERT INTO countries (id, name, continent) VALUES (23, 'El Salvador', 'North America');
INSERT INTO countries (id, name, continent) VALUES (24, 'Falkland Islands (Islas Malvinas)', 'South America');
INSERT INTO countries (id, name, continent) VALUES (25, 'French Guiana', 'South America');
INSERT INTO countries (id, name, continent) VALUES (26, 'Grenada', 'North America');
INSERT INTO countries (id, name, continent) VALUES (27, 'Guadeloupe', 'North America');
INSERT INTO countries (id, name, continent) VALUES (28, 'Guatemala', 'North America');
INSERT INTO countries (id, name, continent) VALUES (29, 'Guyana', 'South America');
INSERT INTO countries (id, name, continent) VALUES (30, 'Haiti', 'North America');
INSERT INTO countries (id, name, continent) VALUES (31, 'Honduras', 'North America');
INSERT INTO countries (id, name, continent) VALUES (32, 'Jamaica', 'North America');
INSERT INTO countries (id, name, continent) VALUES (33, 'Martinique', 'North America');
INSERT INTO countries (id, name, continent) VALUES (34, 'Montserrat', 'North America');
INSERT INTO countries (id, name, continent) VALUES (35, 'Netherlands Antilles', 'North America');
INSERT INTO countries (id, name, continent) VALUES (36, 'Nicaragua', 'North America');
INSERT INTO countries (id, name, continent) VALUES (37, 'Panama', 'North America');
INSERT INTO countries (id, name, continent) VALUES (38, 'Paraguay', 'South America');
INSERT INTO countries (id, name, continent) VALUES (39, 'Peru', 'South America');
INSERT INTO countries (id, name, continent) VALUES (40, 'Puerto Rico', 'North America');
INSERT INTO countries (id, name, continent) VALUES (41, 'Saint Kitts and Nevis', 'North America');
INSERT INTO countries (id, name, continent) VALUES (42, 'Saint Lucia', 'North America');
INSERT INTO countries (id, name, continent) VALUES (43, 'Saint Vincent/Grenadines', 'North America');
INSERT INTO countries (id, name, continent) VALUES (44, 'Suriname', 'South America');
INSERT INTO countries (id, name, continent) VALUES (45, 'Trinidad and Tobago', 'North America');
INSERT INTO countries (id, name, continent) VALUES (46, 'Turks and Caicos Islands', 'North America');
INSERT INTO countries (id, name, continent) VALUES (47, 'Uruguay', 'South America');
INSERT INTO countries (id, name, continent) VALUES (48, 'Venezuela', 'South America');
INSERT INTO countries (id, name, continent) VALUES (49, 'Virgin Islands,  U.S.', 'North America');
INSERT INTO countries (id, name, continent) VALUES (50, 'Virgin Islands, British', 'North America');
INSERT INTO countries (id, name, continent) VALUES (51, 'Albania', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (52, 'Austria', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (53, 'Belgium', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (54, 'Bosnia and Herzegovina', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (55, 'Bulgaria', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (56, 'Croatia', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (57, 'Cyprus', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (58, 'Czech Republic', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (59, 'Denmark', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (60, 'Faroe Islands', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (61, 'Finland', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (62, 'Former Serbia and Montenegro', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (63, 'France', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (64, 'Germany', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (65, 'Gibraltar', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (66, 'Greece', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (67, 'Hungary', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (68, 'Iceland', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (69, 'Ireland', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (70, 'Italy', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (71, 'Luxembourg', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (72, 'Macedonia', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (73, 'Malta', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (74, 'Netherlands', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (75, 'Norway', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (76, 'Poland', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (77, 'Portugal', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (78, 'Romania', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (79, 'Slovakia', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (80, 'Slovenia', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (81, 'Spain', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (82, 'Sweden', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (83, 'Switzerland', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (84, 'Turkey', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (85, 'United Kingdom', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (86, 'Armenia', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (87, 'Azerbaijan', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (88, 'Belarus', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (89, 'Estonia', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (90, 'Georgia', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (91, 'Kazakhstan', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (92, 'Kyrgyzstan', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (93, 'Latvia', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (94, 'Lithuania', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (95, 'Moldova', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (96, 'Russia', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (97, 'Tajikistan', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (98, 'Turkmenistan', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (99, 'Ukraine', 'Europe');
INSERT INTO countries (id, name, continent) VALUES (100, 'Uzbekistan', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (101, 'Bahrain', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (102, 'Iran', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (103, 'Iraq', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (104, 'Israel', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (105, 'Jordan', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (106, 'Kuwait', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (107, 'Lebanon', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (108, 'Oman', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (109, 'Palestine', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (110, 'Qatar', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (111, 'Saudi Arabia', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (112, 'Syria', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (113, 'United Arab Emirates', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (114, 'Yemen', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (115, 'Algeria', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (116, 'Angola', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (117, 'Benin', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (118, 'Botswana', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (119, 'Burkina Faso', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (120, 'Burundi', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (121, 'Cameroon', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (122, 'Cape Verde', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (123, 'Central African Republic', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (124, 'Chad', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (125, 'Comoros', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (126, 'Congo (Brazzaville)', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (127, 'Congo (Kinshasa)', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (128, 'Cote dIvoire (IvoryCoast)', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (129, 'Djibouti', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (130, 'Egypt', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (131, 'Equatorial Guinea', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (132, 'Eritrea', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (133, 'Ethiopia', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (134, 'Gabon', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (135, 'Gambia, The', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (136, 'Ghana', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (137, 'Guinea', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (138, 'Guinea-Bissau', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (139, 'Kenya', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (140, 'Lesotho', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (141, 'Liberia', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (142, 'Libya', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (143, 'Madagascar', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (144, 'Malawi', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (145, 'Mali', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (146, 'Mauritania', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (147, 'Mauritius', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (148, 'Morocco', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (149, 'Mozambique', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (150, 'Namibia', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (151, 'Niger', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (152, 'Nigeria', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (153, 'Reunion', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (154, 'Rwanda', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (155, 'Saint Helena', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (156, 'Sao Tome and Principe', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (157, 'Senegal', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (158, 'Seychelles', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (159, 'Sierra Leone', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (160, 'Somalia', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (161, 'South Africa', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (162, 'Sudan', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (163, 'Swaziland', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (164, 'Tanzania', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (165, 'Togo', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (166, 'Tunisia', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (167, 'Uganda', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (168, 'Western Sahara', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (169, 'Zambia', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (170, 'Zimbabwe', 'Africa');
INSERT INTO countries (id, name, continent) VALUES (171, 'Afghanistan', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (172, 'American Samoa', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (173, 'Australia', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (174, 'Bangladesh', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (175, 'Bhutan', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (176, 'Brunei', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (177, 'Burma (Myanmar)', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (178, 'Cambodia', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (179, 'China', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (180, 'Cook Islands', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (181, 'Fiji', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (182, 'French Polynesia', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (183, 'Guam', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (184, 'Hong Kong', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (185, 'India', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (186, 'Indonesia', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (187, 'Japan', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (188, 'Kiribati', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (189, 'Korea, North', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (190, 'Korea, South', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (191, 'Laos', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (192, 'Macau', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (193, 'Malaysia', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (194, 'Maldives', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (195, 'Mongolia', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (196, 'Nauru', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (197, 'Nepal', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (198, 'New Caledonia', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (199, 'New Zealand', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (200, 'Niue', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (201, 'Pakistan', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (202, 'Papua New Guinea', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (203, 'Philippines', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (204, 'Samoa', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (205, 'Singapore', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (206, 'Solomon Islands', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (207, 'Sri Lanka', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (208, 'Taiwan', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (209, 'Thailand', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (210, 'Timor-Leste (East Timor)', 'Asia');
INSERT INTO countries (id, name, continent) VALUES (211, 'Tonga', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (212, 'U.S. Pacific Islands', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (213, 'Vanuatu', 'Oceania');
INSERT INTO countries (id, name, continent) VALUES (214, 'Vietnam', 'Asia');